name "graphite"
maintainer       "Scott M. Likens"
maintainer_email "scott@likens.us"
license          "Apache 2.0"
description      "Installs/Configures graphite"
supports 'ubuntu', "= 12.04"
version          "0.1.0"
depends "python"
depends "carbon", "0.1.0"
depends "git"
depends "runit"
