#+STARTUP: showeverything :vlines t
#+TITLE: Graphite Web Interface Cookbook
#+AUTHOR: Scott M. Likens
#+EMAIL: scott@likens.us

* Goals
  To provide a supportable _pattern_ to automate hosting the Django Application of the [[http://graphite.wikidot.com/][Graphite]] product.  This cookbook will depend softly on [[https://github.com/damm/carbon][carbon]] cookbook to configure any _carbon(relay|cache)_ instances.

** Requirements:
   [[http://www.opscode.com/chef/][Chef 0.10.8+]]  
   Upstart

** Usage:
   TBD


*** Author::
    Scott M. Likens [[mailto:scott@spam.likens.us][<scott@likens.us>]]


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
  
