name "graphite"
maintainer       "Scott M. Likens"
maintainer_email "scott@likens.us"
license          "Apache 2.0"
description      "Installs/Configures graphite"

version          "0.0.6"
depends "carbon"
depends "git"
depends "python"
depends "graphite"
